### ISSUE TITLE
RAPI over I2C

### ISSUE THREAD

**Issue by wecansu** [lincomatic/open_evse#104]
Hello. I wanted to try openEVSE remote control via I2C and I did not succeed. I uncommented the line "#define RAPI_I2C", and tried to use the STM32 board as an I2C master, to manage openEVSE. It did not work. Having studied the code, I realized that openEVSE itself would be an I2C master, and for remote control I should have a slave device. Is this true?
If so, this is not good for my project. I need to manage 3-4 openEVSE single board and I would like to see it as an I2C master device, and all openEVSE is a slave. Is it possible to do this?

**Comment by lincomatic** [comment]
Sorry, I don't have time to implement and test changes to RAPI over I2C. It was mainly done to facilitate testing, and as such, is an unsupported feature.
