### ISSUE TITLE
$AT event not sent while sleeping

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#115]
Just been testing the latest dev firmware (D6.1.3) and I noticed that the `$AT` async event is not sent if the connected flag changes while sleeping but is updated correctly via `$GS`.

**Comment by lincomatic** [comment]
Duly noted. The $AT events are not sent out as frequently as they should be. I need to fix that. The problem is that there's no more code space left w/ the current default parameters to make any new changes to the firmware

**Comment by lincomatic** [comment]
https://github.com/lincomatic/open_evse/commit/faf39ff78fb322cf4505e023831f7798398c2887
