### ISSUE TITLE
Current is only sampled while charging

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#116]
Note: this is probably not an issue as it is  not something that should happen in a real setup.

I have been using a signal generator to fake the current CT, which looks to be working well, however I have noticed that the current is only sampled (and hence the over current error detection) when the EVSE is charging.

Obviously in a real setup the relay would disconnect the power and if it doesn't there is probably not a lot the EVSE can do, but highlighting just in case it is an oversight.

**Comment by lincomatic** [comment]
Yes, the code is intentionally designed to read the current only when charging. We have stuck relay detection to detect if the relay is welded closed, so is there really a need to waste CPU cycles on the ammeter when the relay is open?
