### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sorphin** [lincomatic/open_evse#119]
In your most recent changes, you added SetAmmeterDirty to:

#endif //Adafruit RGB LCD
        // n.b. blue LED is on
-->        SetAmmeterDirty(1); // force ammeter update code below
        break;
      case EVSE_STATE_D: // vent required

without an ifdef for AMMETER.. (I'd have just submitted a diff, but my tree is far off from yours with my mods line number wise.

**Comment by lincomatic** [comment]
Thanks https://github.com/lincomatic/open_evse/commit/0d6247c3ce1d6803bdf0eaa1078a56a7e5cd5a45
