### ISSUE TITLE
Random resets after D7.1.3 upgrade

### ISSUE THREAD

**Issue by kallisti5** [lincomatic/open_evse#140]
Seeing random "resets" while charging after upgrading my OpenEVSE from 5.0.1 to D7.1.3

I only noticed because I was nearby and head the OpenEVSE contractors open, close in the middle of a charge.    I've heard this happen a few times now while charging my Bolt EV from 52% to 80% at 32A

The only data i've been able to capture so far is a few screenshots of "before and right after" the contactor open.

![photo_2021-04-22_09-58-08](https://user-images.githubusercontent.com/100110/115736925-4d549780-a351-11eb-8231-60d08e26a578.jpg)
![photo_2021-04-22_09-58-13](https://user-images.githubusercontent.com/100110/115736941-504f8800-a351-11eb-9660-cffa47c2c3db.jpg)
![photo_2021-04-22_09-58-17](https://user-images.githubusercontent.com/100110/115736949-534a7880-a351-11eb-8ca5-22cda30124cb.jpg)

**Comment by kallisti5** [comment]
Hm.  The center of the J1772 is running ~84C while charging.  That's pretty much the top of the spec.   Maybe i'm triggering some thermal shutdown?

**Comment by lincomatic** [comment]
84C is very hot. The panic temperature is 71C, and will cause the contactor to open until it cools down. You need to open up your case and figure out where the heat is coming from. You probably have a wire that's not connected properly

**Comment by kallisti5** [comment]
For any future lurkers.  This is the cable I used:
https://www.amazon.com/gp/product/B07YD2LBZW

You can't open the J1772 connector, it's sealed closed.  I'd avoid connectors of that design at all costs.  I checked the purchase date... it went through minimal abuse (pandemic) for a little over a year before wearing to the point it gets 84C in ~1 hour.

**Comment by kallisti5** [comment]
The handle was pretty boring, but actually looked like it was constructed with care. The fault was the design on the pins.  They're solid metal tubes with a web of fine 0.35mm fingers that ride the pin.

After around a year of use, i'm guessing the fingers just "give out" making the few remaining ones touching the pin to heat up.  My other J1772's all have thick 2mm fingers that are wrapped in spring steel to keep them tight.

![E1oMZ38WEAIgm1X](https://user-images.githubusercontent.com/100110/118654520-441ee500-b7ae-11eb-8774-6816c5fcf1b3.jpg)
![E1oMaLyXIAkvjA5](https://user-images.githubusercontent.com/100110/118654538-484b0280-b7ae-11eb-876a-78efc331af1c.jpg)
![E1oOtDTWUAIE6NE](https://user-images.githubusercontent.com/100110/118654559-4c772000-b7ae-11eb-8c20-2a23d7e866ad.jpg)

**Comment by lincomatic** [comment]
Yikes, what a piece of junk!
