### ISSUE TITLE
RAPI Command Serial Numbers

### ISSUE THREAD

**Issue by chris1howell** [lincomatic/open_evse#143]
RAPI command to SET and GET Serial Numbers required by OCPP.

station chassis
connector
meter

Proposed format
SET command write once only if EEPROM serial numbers are blank. EEPROM could also be written directly with programmer. 
$SS _station connector meter_

GET
$GS
$OK _station connector meter_

**Comment by lincomatic** [comment]
IMHO, this info should be handled by the WiFi module. The EVSEs aren't involved in OCPP at all. You should just use the MAC address as the serial number.

**Comment by chris1howell** [comment]
OCPP requires the serial number for the station, connector and energy
meter.

The energy meter is physically built into the controller and should have a
serial number even if there is no WiFi or OCPP. It does not make sense to
store this number on WiFi when the hardware is physically on the controller.

The connector serial number should also be burned to the controller, again
the charge connector is physically part of the controller should have a
serial number even if there is no WiFi or OCPP.

The chassis serial number is arbitrary and can be store wherever. But every
station chassis should have a serial number even if it does not have WiFi.

**Comment by jeremypoulter** [comment]
FYI, the ATMEGA 328 may has a unique ID we can use: https://www.thethingsnetwork.org/forum/t/arduino-has-a-unique-id/21415

**Comment by lincomatic** [comment]
> FYI, the ATMEGA 328 may has a unique ID we can use: https://www.thethingsnetwork.org/forum/t/arduino-has-a-unique-id/21415

I looked into this... interesting idea. The first 6 bytes are ASCII, followed by 4 hex bytes. It's guaranteed to be unique only in the 328PB, but some people are using it, anyway. In the 328P, the first of the hex bytes is always FF

**Comment by lincomatic** [comment]
There's a library for this: https://github.com/ricaun/ArduinoUniqueID
Maybe you guys could try running it on a bunch of boards and see if it looks unique enough to use?

**Comment by jeremypoulter** [comment]
Will give it a go on the boards I have, but that being said I believe the primary focus of this is new boards so I would assume we can build these with the 328PB @chris1howell ?

**Comment by lincomatic** [comment]
The PB is functionally identical. The pinouts are almost identical, but therre's a pin or two that need to be strapped. Also, you need to either get a newer copy of avrdude, or modify the config to work w/ its chip id, which is different. the PB is generally cheaper, BTW. I'll upload code in a bit.. implemented a $GI command to get the ID

**Comment by jeremypoulter** [comment]
In #114 I have a config that builds with the latest Arduino will see which avrdude is used.

**Comment by lincomatic** [comment]
https://github.com/lincomatic/open_evse/commit/b035a34d197b8b4d2a627b7955e20d472d401de4

**Comment by jeremypoulter** [comment]
Gave this a try `$GI` gives `$NK^21`, think you have it as `$SI` by mistake and also the command is echoed back so passing `$SI` gives `$OK $SI Y91017FF14011C^0F`, but on the positive side I do indeed get different different codes on the different devices, `Y57414FF020F0C` and `Y91017FF14011C`

**Comment by lincomatic** [comment]
Oops, sorry about that. I changed it from $SI to $GI. Glad that it's giving different values on different boards. I guess the question is how unique they really are. Anyway, let's just try using this for now.

**Comment by lincomatic** [comment]
Sorry, I just noticed that the response is echoing the command in your examples above.. it shouldn't be responding $OK $GI.
I just pushed a fix for that: https://github.com/lincomatic/open_evse/commit/a5db0a49464ea0c155821f1f362bea90a6be80c5
My apologies, I don't have a hardware setup with me at the moment to test the code, so I was pushing untested commits.
