### ISSUE TITLE
Extra space in `$GI` response

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#146]
I nave noticed that there is an extra space in the return of the `$GI` command, eg for my test board I get:

```
$OK  Y57414FF020F0C^4D
```

**Comment by lincomatic** [comment]
Not sure what's going on with yours. 
There's no extra space with mine:

$OK U17246FF031C12

**Comment by lincomatic** [comment]
If you' have any more issues, you can reopen it. I'm going to assume it's resolved, since there hasn't been any feedback
