### ISSUE TITLE
GetChargingCurrent returns last charging current after charging

### ISSUE THREAD

**Issue by CapnBry** [lincomatic/open_evse#15]
I thought there was a measurement error occurring in the GetChargingCurrent() function because my OpenEVSE was always reporting 880-1100mA power usage. I didn't put two and two together for a few days when I realized it worked fine before a charge, it was just after the charge it always reported current use.

Looking at the code, I see that the m_ChargingCurrent variable is only updated in EVSE_STATE_C (charging state). When the charge completes, it stops updating the value, leaving it at the last value right before the charge cycle completed. The simple fix would be to add
https://github.com/lincomatic/open_evse/blob/development/open_evse.pde#L1233
~~~
void J1772EVSEController::chargingOff()
{
...
#ifdef AMMETER
  m_ChargingCurrent = 0;
#endif
}
~~~

This covers all other state transitions where the relay is shut off. I'd submit a pull request but it seems silly for a one line change.

**Comment by lincomatic** [comment]
Thanks! merging it now.
