### ISSUE TITLE
OpenEVSE start full amp when changing state from disable to active

### ISSUE THREAD

**Issue by KipK** [lincomatic/open_evse#155]
Something wrong to track down here, seems while OpenEvse is changing its state from disable to enable, it starts a charge with full amp, ignoring the Pilot value set from wifi module. Pilot is still displaying ok the requested value.

Reclaiming the charge_current will then set the charge to correct current.

I have made a little hack to mitigate this for now ( https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/532 ) but there's still a 3sec glitch where it will starts full amp. Would be better to fix this here.

**Comment by lincomatic** [comment]
There is no code to change the current capacity when EVSE is enabled. You can look at the code yourself in J1772EvseController::Enable(). Maybe you're talking about during boot. I have mitigated this with BOOTLOCK

**Comment by lincomatic** [comment]
OK so I will mark this closed
