### ISSUE TITLE
Possibilty to set the current more precisely ?

### ISSUE THREAD

**Issue by SmartEVLab** [lincomatic/open_evse#158]
Hello, I want to set the charging current of an openevse wallbox with the command $SC from the RAPI protocol. Currently, the command allows to set the charging current by step of 1A. I would like to set it by step of 0.1 A, but I know that the command $SC only takes integer. Is it possible to to set the current more precisely ?

**Comment by lincomatic** [comment]
The code is done it integer, and doesn't support floats. I don't even know if J1772 allows fractional currents. Another consideration is the granularity of the clock. Sorry, this isn't something that I have time to look into.
