### ISSUE TITLE
The energy history is extremely chatty

### ISSUE THREAD

**Issue by goldserve** [lincomatic/open_evse#159]
The logging information for energy should be collapsed to plug and unplug event. Right now, individual events are being captured every time charging starts and stops but solar divert will do that. Makes it hard to figure out how much energy was put into the car during one plug/unplug session.

**Comment by jeremypoulter** [comment]
I think this is a web UI issue please open on 
https://github.com/OpenEVSE/ESP32_WiFi_V4.x
