### ISSUE TITLE
missing I2C temperature sensors

### ISSUE THREAD

**Issue by KipK** [lincomatic/open_evse#163]
Latest compiled master seems to miss i2c T° sensor from LCD ( or led extension ) .
Switching back to previous version ( 8.2.2 ) is ok. 

I'm trying to track down what could introduce this issue but haven't found yet. 

I've added a msg on 8.2.3 pre-release to prevent people upgrading until it's solved.

**Comment by glynhudson** [comment]
I can confirm I'm able to replicate the issue, I'm testing with an older LCD display with a MCP9808 sensor (temp2) and a MCP9808 external sensor connected to the OpenEVSE WiFi V1 ESP32 (temp4)

Running 8.2.2.EU (V8.2.0 Lincomatic) Temp1 and Temp4 are available. 

![8 2 2 0 with ESP32 I2c](https://user-images.githubusercontent.com/758844/233145223-43599c07-633e-4cb9-ba9f-8b150db2460a.png)


Flashing 8.2.3.EU (V8.2.1 Lincomatic) only Temp4 is available, the controller is no longer reading from the MCP9808:

![8 2 3](https://user-images.githubusercontent.com/758844/233145263-4eaba88a-4b12-4bc9-9ed9-4d12d43b33ea.png)
