### ISSUE TITLE
Substitute RGB LCD for monochrome LCD with PCF8574 interface module

### ISSUE THREAD

**Issue by pablogomezgracia** [lincomatic/open_evse#167]
Hello lincomatic,
First of all, thank you for your help and your work on this project.
My issue is regarding the installation of a monochrome LCD in the system. I have substituted the OpenEVSE RGB LCD for a monochrome LCD with a PCF8574 interface module. 
So far, the LCD powers on with a white screen and blinks everytime I load the firmware or plug the board, but text won't show up in the screen. I think communication is fine because if I change the LCD_I2C_ADDR, the screen won't blink everytime I load the firmware. So address 0x27 seems to be the correct address. 
The changes I've made in the code are:

**Comment by pablogomezgracia** [comment]
-main.cpp: uncomment line 54: #include "./LiquidCrystal_I2C.h"
-

**Comment by pablogomezgracia** [comment]
The changes I've made in the code are:
- main.cpp: uncomment line 54: #include "./LiquidCrystal_I2C.h"
- open_evse.h: comment line 238  //#define DEFAULT_LCD_BKL_TYPE BKL_TYPE_RGB and uncomment line 239 #define DEFAULT_LCD_BKL_TYPE BKL_TYPE_MONO.  Uncomment line 247 #define I2CLCD_PCF8574 which defines I2CLCD and undefines RGBLCD.

The LCD and interface module I'm using is https://www.az-delivery.de/en/products/bundlelcd-schnittstelle 
I don't know if i'm missing something or it's just that the interface module is not supported. In that case, which LCDs/I2C interface modules could I use for this project?
Thank you very much,
Pablo

**Comment by pablogomezgracia** [comment]
My bad...solved!!!!

**Comment by lincomatic** [comment]
there is no standard way to assign the data lines, so some modules need to have the #defines changed. I'm curious, now did you fix it in your case?
