### ISSUE TITLE
OpenEvse trigger GFCI Fault with test disabled 

### ISSUE THREAD

**Issue by DylanVautrin** [lincomatic/open_evse#172]
Hello,
We have some issue using OpenEVSE, when we try to start a session, it goes in faulted GFCI (GFI more precisely), even with the test disabled in the GUI, we are sure about our electric installation. Can you help us, please ? We have multiple board, and it doesn't happen on every board, so we really don't understand why, technically, with the test disabled we shouldn't get this error no ?
Thanks in advance.
Best regards

**Comment by lincomatic** [comment]
Disabling GFI self test only disables the self test at POST. It doesn't disable GFI functionality, because that's required at all times. Check your GFI hardware. This is not a firmware issue
