### ISSUE TITLE
Service level display issue

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#64]
When cycling around the Service level menu options the + is initially correct, but on looping round it moves to the previous option, eg if the service level is 2, the following is displayed on each press of the button;

- +2
- Auto
- +1
- 2

see https://youtu.be/O1HNXLJIG9A

**Comment by lincomatic** [comment]
Thanks. Resolved in https://github.com/lincomatic/open_evse/commit/4656f87d193e386b3555c2aa1df2fe70fa5668fe
