### ISSUE TITLE
Setting the charge/time limit via RAPI does not update LCD

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#65]
When setting the charge or time limit via RAPI the LCD does not update to show the lightning/clock icon. Entering/exiting the menu then displays the icons as expected.

**Comment by lincomatic** [comment]
Hmm, it seems to work on mine. Have you tested the dev branch?

**Comment by lincomatic** [comment]
Oops, I misread your report above. Fixed in https://github.com/lincomatic/open_evse/commit/8433379c2a3cdd1e7fc0ec525408a0a33d47a176
