### ISSUE TITLE
Setting the LCD text via RAPI can corrupt display

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#66]
When setting the LCD text via RAPI (eg '$FP 0 0 Client-IP.......') the display can get corrupted depending on the state of OpenEVSE, eg;

![2017-07-21 13 18 37](https://user-images.githubusercontent.com/6116992/28463275-8455bc14-6e17-11e7-9b9f-fc888be8bbe3.jpg)
![2017-07-21 13 19 22](https://user-images.githubusercontent.com/6116992/28463277-86537ec0-6e17-11e7-84ca-1376c7bc0da7.jpg)

Could we add an RAPI command to claim/release the the LCD? When claimed the LCD will only be updated via RAPI (using $FP, $FB). On release the LCD will revert back to OpenEVSE control.

**Comment by glynhudson** [comment]
I think the same issue has been reported here, it seems the openevse FW stable production branch is on the openevse github: https://github.com/OpenEVSE/open_evse/pull/4

**Comment by lincomatic** [comment]
Please have a look at the $F0 command in the dev branch. It does what you need
