### ISSUE TITLE
$FP command causes crash

### ISSUE THREAD

**Issue by jeremypoulter** [lincomatic/open_evse#72]
Print more than 6 spaces on the LCD using $FP causes a crash, eg "$FP 0 1 IP Address      "

This is probably because the array of tokens is 10. So one possible fix would be to make this 20, but a simpler solution maybe to just stop token parsing when the max is reached, the last token would then included the remaining spaces.

**Comment by lincomatic** [comment]
Thanks. I added code to just fail gracefully when there are more tokens than we can swallow
https://github.com/lincomatic/open_evse/commit/23daeb50066052b9d14b874fc4ad65261a181593
