### ISSUE TITLE
extended_fuses setting causes unreliable booting

### ISSUE THREAD

**Issue by AntaresAdroit** [lincomatic/open_evse#78]
The setting for the _openevse.bootloader.extended_fuses_ property in the  _boards.txt.arduino1.6.x_ should be 0x04, not 0x05. The 0x05 value causes unreliable booting for many OpenEVSE units. See this issue on the openEVSE support site for more details.

https://openev.freshdesk.com/support/discussions/topics/6000051632

**Comment by lincomatic** [comment]
Thanks, I just found out about this a few days ago. Didn't have time to push the change.
It's done now. Thanks.

https://github.com/lincomatic/open_evse/commit/1b730fadbc3b522d658a3cec1712a0bb3fd2ab32
