### ISSUE TITLE
$FS 'rebounds' when trying to pause a delay timer charge

### ISSUE THREAD

**Issue by glynhudson** [lincomatic/open_evse#89]
If a delay timer charge is active i.e the current charging session was started by the start time on the delay timer then issuing `$FS` to pause the charge results in the charge being momentarily stopped then re-started 1s later, presumably by the delay timer.  

Interestingly, pressing the button to pause the charge when a delay timer charge is active works as expected: the charge stops, delay timer is overridden. 

Is this intended behaviour? IMO is would be best if `$FS` has the same effect as a button press, overriding the delay timer.

**Comment by lincomatic** [comment]
pushed fix to dev branch in D5.0.0
