### ISSUE TITLE
Where can I find eeprom_24.bin?

### ISSUE THREAD

**Issue by DeltaVetal26** [lincomatic/open_evse#91]
Hi! I want to test the latest version of the OpenEVSE firmware, but I can not figure out where to get eeprom_24.bin? As far as I understand, with each version of the firmware the contents of this file change or can I use this file with v4.8.0?

**Comment by lincomatic** [comment]
I have no idea where this EEPROM file cines from. Perhsps it's someone's pre-configuration. No EEPROM file is needed, as long as you let avrdude erase the EEPROM when programming the firmware, which is what happens when you use the defaults
